# Generated by Django 5.0.1 on 2024-02-03 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MMDInfo',
            fields=[
                ('Index', models.IntegerField(primary_key=True, serialize=False)),
                ('Title', models.CharField(default='', max_length=100)),
                ('TitleEng', models.CharField(blank=True, default='', max_length=100)),
                ('Artist', models.CharField(default='', max_length=100)),
                ('Cover', models.CharField(blank=True, default='', max_length=200)),
                ('Type', models.CharField(blank=True, default='', max_length=20)),
                ('Player', models.IntegerField(default=1)),
                ('Motion', models.CharField(blank=True, default='', max_length=100)),
                ('MotionEdited', models.BooleanField(default=False)),
                ('Facial', models.CharField(blank=True, default='', max_length=100)),
                ('Lipsync', models.CharField(blank=True, default='', max_length=100)),
                ('Camera', models.CharField(default='', max_length=100)),
                ('CameraEdited', models.BooleanField(default=False)),
            ],
        ),
    ]
