# Generated by Django 5.0.1 on 2024-02-04 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickaccess', '0002_alter_mmdquickfavorites_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mmdquickfavorites',
            name='id',
        ),
        migrations.AlterField(
            model_name='mmdquickfavorites',
            name='Username',
            field=models.CharField(default='', max_length=100, primary_key=True, serialize=False),
        ),
    ]
